name: Manual Pipeline

on:
  workflow_dispatch:

jobs:
  test-execution:
    runs-on: ubuntu-latest

    steps:
      # clone repository
      - name: Clone repository
        uses: actions/checkout@v4

      # Configure node.js
      - name: Configure node js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Automation Test Execution
      - name: Automation Test Execution
        run: npm test